#sbs-git:slp/pkgs/m/mpfr mpfr 3.0.0-9slp2+s1 85699ee05033bdf75074a2234996cba6bc7b41b0
# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       mpfr
Summary:    A C library for multiple-precision floating-point computations
Version:    3.0.0
Release:    1.1
Group:      System/Libraries
License:    LGPLv3+ and GPLv3+
URL:        http://www.mpfr.org/
Source0:    ftp://ftp.gnu.org/gnu/mpfr/%{name}-%{version}.tar.xz
Source1001: packaging/mpfr.manifest 
Patch0:     mpfr-3.0.0-debian.patch
Requires:   gmp >= 4.2.3
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  autoconf
BuildRequires:  libtool
BuildRequires:  mpfr
BuildRequires:  gmp-devel


%description
The MPFR library is a C library for multiple-precision floating-point
computations with "correct rounding". The MPFR is efficient and
also has a well-defined semantics. It copies the good ideas from the
ANSI/IEEE-754 standard for double-precision floating-point arithmetic
(53-bit mantissa). MPFR is based on the GMP multiple-precision library.



%package devel
Summary:    Development tools A C library for mpfr library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The static libraries, header files and documentation for using the MPFR
multiple-precision floating-point library in applications.

If you want to develop applications which will use the MPFR library,
you'll need to install the mpfr-devel package.  You'll also need to
install the mpfr package.



%prep
%setup -q -n %{name}-%{version}

# mpfr-3.0.0-debian.patch
%patch0 -p1
# >> setup
# << setup

%build
cp %{SOURCE1001} .
# >> build pre
# << build pre

%configure --disable-static \
    --disable-assert

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%manifest mpfr.manifest
%defattr(-,root,root,-)
# >> files
%doc COPYING COPYING.LESSER NEWS README
%{_libdir}/libmpfr.so.*
# << files


%files devel
%manifest mpfr.manifest
%defattr(-,root,root,-)
# >> files devel
%doc %{_docdir}/%{name}
%{_libdir}/libmpfr.so
%{_includedir}/*.h
%{_infodir}/mpfr.info*
# << files devel

